### PR TITLE
CMA Issue 3 Adding Knight

### PR DESCRIPTION
**Pull request by caleb-austin**

### CODE REVIEW

**Review by TonePoems — CHANGES_REQUESTED** [review]
Can you add a statement about the knight to the info.txt file? That's the only thing I see.

**Comment by caleb-austin** [comment]
> Can you add a statement about the knight to the info.txt file? That's the only thing I see.

Done. Thanks for the reminder

**Review by TonePoems — APPROVED** [review]
great!

**Review by gbrown97 — APPROVED** [review]
Looks good Caleb!

**Review by nmhijazi15 — APPROVED** [review]
Glad to see more characters introduced in the game!

**Pull request merged**
